--1 添加fld表记录
delete from fld where tabname='syscfg';
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'syscfg',       'keyno',      '键值',           'Name',             0, 1,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'syscfg',       'namec',      '中文名称',       'Name(Chinese)',    0, 2,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'syscfg',       'namee',      '英文名称',       'Name(English)',    0, 3,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'syscfg',       'value',      '键值',           'Value',            0, 4,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'syscfg',       'memo',       '备注',           'Memo',             0, 5,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);


delete from fld where tabname='entity';
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'name',       '实体名',         'Name',             0, 1,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'namec',      '中文名',         'Name(Chinese)',    0, 2,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'namee',      '英文名',         'Name(English)',    0, 3,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'type',       '类型',           'Type',             1, 4,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'major',      '主类型',         'Major',            1, 5,1,1,1,0, 1, '1',  null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'minor',      '子类型',         'Minor',            1, 6,1,1,1,0, 1, '0',  null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'domain',     '域',             'Domain',           1, 7,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'tabgrp',     '图形表名',       'Graph Table',      0, 8,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'tabatt',     '属性表名',       'Att Table',        0, 9,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'glmaj',      '关联主类型',     'Major',            1,10,1,1,1,0, 1, '0',  null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'glmin',      '关联子类型',     'Minor',            1,11,1,1,1,0, 1, '0',  null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'log',        '记录日志',       'Need Log',         1,12,2,1,1,0, 1, '0',  null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'keywid',     'Key 列宽',       'Key Width',        0,13,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'entity',       'func',       '关联功能',       'Functions',        0,14,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);


delete from fld where tabname='fld';
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'sys',        '系统号',         'System No',        0, 1,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'tabname',    '数据表名',       'Table Name',       0, 2,1,1,0,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'colname',    '列名',           'Column Name',      0, 3,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'namec',      '中文名',         'Name(Chinese)',    0, 4,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'namee',      '英文名',         'Name(English)',    0, 5,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'isnum',      '是否数值型',     'Is Number',        1, 6,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'disporder',  '排列位置',       'Display Order',    1, 7,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'disptype',   '显示类型',       'Display Type',     1, 8,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'newedit',    '新输入可编辑',   'New Editable',     1, 9,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'editable',   '是否可编辑',     'Editable',         1,10,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'nullable',   '是否可空',       'Nullable',         1,11,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'disprows',   '显示行数',       'Display Row(s)',   1,12,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'minval',     '最小值',         'Minimun Value',    0,13,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'maxval',     '最大值',         'Maximun Value',    0,14,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'defval',     '默认值',         'Default Value',    0,15,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'minlen',     '最小长',         'Minimun Length',   1,16,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'maxlen',     '最大长',         'Maximun Length',   1,17,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'groupe',     '组名英文',       'Group(English)',   0,18,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'groupc',     '组名中文',       'Group(Chinese)',   0,19,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'qrylevel',   '查询级别',       'Query Level',      1,20,2,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'bzfld',      '标注字段',       'Lable Fld',        1,21,2,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fld', 	      'ismcard',    '卡片显示字段',   'Card Fld',         1,22,2,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);


delete from fld where tabname='fldvalue';
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'sys',        '系统号',         'System No',        0, 1,1,1,0,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'tabname',    '数据表名',       'Table Name',       0, 2,1,1,0,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'colname',    '列名',           'Column Name',      0, 3,1,1,0,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'disporder',  '排列位置',       'Display Order',    1, 4,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'dbvalue',    '对应值',         'Database Value',   0, 5,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'dispc',      '显示中文',       'Display(Chinese)', 0, 6,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'fldvalue',     'dispe',      '显示英文',       'Display(English)', 0, 7,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);


delete from fld where tabname='plugin';
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'sys',        '系统号',         'System No',        0, 1,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'name',       '名称',           'Name',             0, 2,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'namee',      '插件英文名',     'Name(English)',    0, 3,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'namec',      '插件中文名',     'Name(Chinese)',    0, 4,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'titlee',     '插件英文标题',   'Title(English)',   0, 5,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'titlec',     '插件中文标题',   'Title(Chinese)',   0, 6,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'closeable',  '是否可关闭',     'Closeable',        1, 8,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'uitype',     '界面类型',       'Ui Type',          1,11,2,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'widgets',    '插件容器',       'Container',        0,13,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'runn',       '多例运行',       'Multiple',         1,14,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'dir',        '插件所在目录',   'Dir',              0,17,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'classurl',   '类文件',         'Class File',       0,18,1,1,1,0, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'icon',       '图标文件',       'Icon',             0,21,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'service',    '服务名',         'Service',          0,25,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'initpara',   '初始化参数',     'Init Param',       0,26,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'height',     '高度',           'height',          0,27,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'width',      '宽度',           'width',           0,28,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'modal',      '是否模态对话框',   'modal',           0,29,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
insert into fld(sys,tabname,colname,namec,namee,isnum,disporder,disptype,newedit,editable,nullable,disprows,minval,maxval,defval,minlen,maxlen,groupe,groupc,qrylevel,bzfld) values('99',     'plugin',       'type',       '组件或者插件',     'type',           0,30,1,1,1,1, 1, null, null, null, 0, 0, null, null, 0, 0);
