--1 往plugin表写plugin记录
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'CopyPlugin',           NULL, '', '模版插件',     1, 0, NULL,                                                        1, '', 'CopyPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'login',                NULL, '', '登录',           1, 0, NULL,                                                        1, '', 'LoginPlugin',          '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'MemberInfoPlugin',     NULL, '', '个人信息',     1, 0, NULL,                                                        1, '', 'MemberInfoPlugin',     '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'MemberResetPwdPlugin', NULL, '', '重置密码',     1, 0, NULL,                                                        1, '', 'MemberResetPwdPlugin', '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'PhotoBrowse',          NULL, '', '相片浏览',     1, 0, NULL,                                                        1, '', 'PhotoBrowsePlugin',    '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'WebViewPlugin',           NULL, '', '网页浏览',     1, 0, NULL,                                                        1, '', 'WebViewPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);

INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'main',                 NULL, '', '主界面',        1, 0, '["HomeWidget1","HomeWidget2","HomeWidget3","HomeWidget4"]', 1, '', 'MainPlugin',           '', '', '{"hideBackButton":1,"showNavigationBar":1,"bottomIconText":{"0xe615":"首页","0xe60f":"评分","0xe655":"邀约","0xe618":"我的"},"currentIndex":0,"rightButtonIcon":"0xe617"}', '', '', 0, 1);
--2 往plugin表写plugin业务记录
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'jy', 'JYPlugin',           NULL, '', '用户信息',     1, 0, NULL,                                                        1, '', 'JYPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'jy', 'RzzxPlugin',           NULL, '', '认证中心',     1, 0, NULL,                                                        1, '', 'RzzxPlugin',           '', '', '{"list":[{"icon":"0xe675","title":"手机认证","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe674","title":"身份认证","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe63b","title":"支付宝认证","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe61a","title":"微信认证","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe627","title":"服务认证","content":"未认证","plugin":"MemberResetPwdPlugin"}]}',                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'func', 'FuncPlugin',           NULL, '', '功能菜单页',     1, 0, NULL,                                                        1, '', 'FuncPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'pub', 'PublishPlugin',           NULL, '', '发布页',     1, 0, NULL,                                                        1, '', 'PublishPlugin',           '', '', '{"list":[{"icon":"0xe675","title":"主题","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe674","title":"内容","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe63b","title":"时间","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe61a","title":"地点","content":"未认证","plugin":"MemberResetPwdPlugin"},{"icon":"0xe61a","title":"费用","content":"未认证","plugin":"MemberResetPwdPlugin"}],"rightButtonText":"发布"}',                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'xcx', 'XCXPlugin',           NULL, '', '小程序',     1, 0, NULL,                                                        1, '', 'XCXPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'yyxq', 'YYXQPlugin',           NULL, '', '邀约',     1, 0, NULL,                                                        1, '', 'YYXQPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'gz', 'GZPlugin',           NULL, '', '我的关注',     1, 0, NULL,                                                        1, '', 'GZPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'yy', 'SPLTPlugin',           NULL, '', '视频聊天',     1, 0, NULL,                                                        1, '', 'SPLTPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'me', 'CZPlugin',           NULL, '', '充值',     1, 0, NULL,                                                        1, '', 'CZPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'me', 'QBPlugin',           NULL, '', '我的钱包',     1, 0, NULL,                                                        1, '', 'QBPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'me', 'MyFBPlugin',           NULL, '', '我的发布',     1, 0, NULL,                                                        1, '', 'MyFBPlugin',           '', '', NULL,                                                                                                                                                     '', '', 0, 1);

--1 往plugin表写widget记录
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'CopyWidget',           NULL, '', '模版组件',     1, 0, NULL,                                                        1, '', 'CopyWidget',           '', '', NULL,                                                                                                                                                     '', '', 0, 2);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'common', 'DuplicateWidget',      NULL, '', '附件组件',     1, 0, NULL,                                                        1, '', 'DuplicateWidget',      '', '', NULL,                                                                                                                                                     '', '', 0, 2);

INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'home1',  'HomeWidget1',          NULL, '', '主界面组件1', 1, 0, '["CopyWidget","CopyWidget","CopyWidget"]',                  1, '', 'HomeWidget1',          '', '', '{"refresh":1,"loadMore":1,"webview":[{"title":"关注公众号","url":"https://mp.weixin.qq.com/s?__biz=MzI3NjcyODc1Ng==&mid=2247483856&idx=1&sn=9e7e3bd6a33c48e316790a3fd6112945&chksm=eb705f0bdc07d61db455855d3e83d5c04ab09b965aec5cc03bee2e55ac599d4219a4a008418d&token=1861440268&lang=zh_CN#rd"},{"title":"线下活动","url":"https://m.bilibili.com/space/297978042"}],"imageUrl":["https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568540087509&di=60eb37d5e8bfa15e9a1f9e5a56486373&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2Ff30ee5ef8f098a74dcb39db7da984df6235e0e3172536-WEF5AR_fw658","https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1569003220014&di=f5d8ee2a3e8c43a54b8ebe377fd2ad5b&imgtype=0&src=http%3A%2F%2Fs9.rr.itc.cn%2Fr%2FwapChange%2F20165_15_16%2Fa9dmz88925138239855.jpg"]}',                                                         '', '', 0, 2);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'home2',  'HomeWidget2',          NULL, '', '主界面组件2', 1, 0, '["CopyWidget","CopyWidget","CopyWidget"]',                  1, '', 'HomeWidget2',          '', '', '{"refresh":1,"loadMore":1,"imageUrl":"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568519800706&di=65077c4b681512d0e4b67d658a199298&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F7%2F5836b01fd1a89.jpg","imageUrl2":"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568519800704&di=27cf401c95cac82a199d12071d50ceef&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F2018-09-11%2F5b9788884dfcf.jpg"}',                                                         '', '', 0, 2);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'home3',  'HomeWidget3',          NULL, '', '主界面组件3', 1, 0, '["CopyWidget","CopyWidget","CopyWidget"]',                  1, '', 'HomeWidget3',          '', '', '{"refresh":1,"loadMore":1,"imageUrl":"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568519800704&di=dc6237b7edb56e8473de9edbfe882fa0&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2Ff%2F57cd0b6e57f4b.jpg","imageUrl2":"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568519800703&di=2c5a73b85b133f347fc6af0b7709b694&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2Fb%2F588564ddb191d.jpg"}',                                                         '', '', 0, 2);
INSERT INTO plugin(sys, cata, name, pname, titlee,titlec,closeable,uitype,widgets, runn, dir, classurl, icon, service, initpara, height, width, modal, type) VALUES('21', 'home4',  'HomeWidget4',          NULL, '', '主界面组件4', 1, 0, '["CopyWidget","CopyWidget","CopyWidget"]',                  1, '', 'HomeWidget4',          '', '', '{"refresh":1,"loadMore":0,"imageUrl":"assets/images/mine-bg.png","list":[{"icon":"0xe656","title":"认证中心","plugin":"RzzxPlugin"},{"icon":"0xe736","title":"我的关注","plugin":"GZPlugin"},{"icon":"0xe602","title":"客服中心","plugin":"WebViewPlugin","webview":{"title":"关注公众号","url":"https://mp.weixin.qq.com/s?__biz=MzI3NjcyODc1Ng==&mid=2247483856&idx=1&sn=9e7e3bd6a33c48e316790a3fd6112945&chksm=eb705f0bdc07d61db455855d3e83d5c04ab09b965aec5cc03bee2e55ac599d4219a4a008418d&token=1861440268&lang=zh_CN#rd"}},{"icon":"0xe678","title":"我的充值","plugin":"CZPlugin"},{"icon":"0xe631","title":"我的钱包","plugin":"QBPlugin"},{"icon":"0xe611","title":"我的发布","plugin":"MyFBPlugin"},{"icon":"0xe619","title":"小程序","plugin":"XCXPlugin"},{"icon":"0xe655","title":"邀请好友","plugin":"WebViewPlugin","webview":{"title":"邀请好友","url":"https://mp.weixin.qq.com/s?__biz=MzI3NjcyODc1Ng==&mid=2247483856&idx=1&sn=9e7e3bd6a33c48e316790a3fd6112945&chksm=eb705f0bdc07d61db455855d3e83d5c04ab09b965aec5cc03bee2e55ac599d4219a4a008418d&token=1861440268&lang=zh_CN#rd"}}]}',                                                                              '', '', 0, 2);

--2 往plugin表写widget业务记录